main:
  wiki_link : https://www.italiapersonalfinance.it
  metadata_semantic_chunking : url

cleaner_scraper:
  create_sitemap:
    max_depth : 3
    instructions: Find all blog articles, guides, and educational content pages.
    allow_external : False

  return_cleaned_pages:
    article_tag : article
    tags: 
      - h1
      - h2
      - h3
      - h4
      - p

semantic_chunker:
  embedding_model : text-embedding-3-small
  splitter:
    chunk_size : 400
    chunk_overlap: 0
    separators:
      - \n\n
      - \n
      - .
    is_separator_regex : False
  database_name : Financial_Advisor
  collection_name : AfterSemChunking
  vector_store:
    index_name : vector_index
    embedding_key : embedding
    text_key : text
    relevance_score_fn : cosine

hybrid_retrieval:
  retriever:
    search_index_name : fulltext_search_index
    top_k : 10
    fulltext_penalty : 50
    vector_penalty : 50

  reranker:
    model: rerank-v4.0-fast

indexing:
  vector_index:
    type : vector
    path : embedding
    numDimensions : 1536
    similarity : cosine
    name : vector_index
    type_A : vectorSearch
  fulltext_index:
    name : fulltext_search_index
    type : search

generator:
  openai_gen_model : gpt-4o-mini
# ollama_model : qwen3:1.7b; discarded to avoid containers orchestration




